### ISSUE TITLE
Questions about cross attention

### ISSUE THREAD

**Issue by nlpjoe** [JiayuLi-997/IntEL-SIGIR2023#3]
Hello JiayuLi, The implementation of cross attention seems to be inconsistent with the formula in the paper. 
https://github.com/JiayuLi-997/IntEL-SIGIR2023/blob/main/IntEL/src/models/IntEL/IntEL.py#L195

Is there any code that has not been updated？ 

thanks in advance :)

**Comment by JiayuLi-997** [comment]
Thanks for pointing it out. We checked the code and found we used another version of attention structure for IntEL (It's performance is slightly worse than the one used for the final paper).
We have updated the code. And for code consistency, we use a hyper parameter 'cross_attention' to control which structure to use.
